### ISSUE TITLE
Localstack (custom endpoint-url) support

### ISSUE THREAD

**Issue by srgg** [turbot/steampipe-plugin-aws#1050]
**Is your feature request related to a problem? Please describe.**
[Localstack](https://localstack.cloud) requires to use [custom endpoint url](https://docs.localstack.cloud/integrations/aws-cli/). Lack of aws endpoint configuration introduces a huge complexity for steampipe + localstack integration testing.

**Describe the solution you'd like**
It wil be great if custom endpoint url can be specified through plugin configuration mechanism.

**Comment by srgg** [comment]
@cbruno10 Thank you for the quick response.

For my limited Integration testing use case it should be enough to have just one generic endpoint-url  being provided on per connection basis. 

As far as I know there is no extra requirements from Localstack.  But AWS provides [different regional endpoints for the sake of compliance]( https://docs.aws.amazon.com/general/latest/gr/rande.html#view-service-endpoints).  AWS Go lang SDK (googled fro this) has ability to provide custom resolver, here is several useful links:

1. https://www.linkedin.com/pulse/how-setup-golang-aws-sdk-v2-localstack-local-phuc-hai-huynh/
2. https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/

 I have never used any of those, so I definetly not the right guy to decide how it can looks like.


Therefore what I can suggest/request for the simple case I have:
 
There can be a way to set up a default endpoint for all connections, that can be done by supporting environment variable AWS_ENDPOINT (not sure why that is not done by official SDK) (1).
And, nevertheless, should be a way to override default one provided  via AWS_ENDPOINT by specifing endpoint-url for teh parcicular connection (2).

**Comment by srgg** [comment]
@cbruno10 Thank you for pointing out exact place in the code, I've create a PR for the fix. One thing about that - I'm not sure how that change can be tested automatically, I've checked both options: AWS_ENDPOINT env variable and config with endpoit_url -- both seems to me working.

**Comment by cbruno10** [comment]
Thank you for working on and opening a PR so quickly @srgg, great stuff!

While looking around to see if AWS had an environment variable of their own today for the CLI or SDKs for setting an endpoint URL, I came across https://github.com/aws/aws-sdk/issues/229, which contained a [proposal](https://github.com/kdaily/aws-sdk/blob/endpoint-url-configuration-proposal/proposals/configure-endpoint-url.md) from the AWS team on how to handle setting custom endpoints overall. Interestingly, they proposed adding config and environment variable support per service, with some alternative solutions for setting a global endpoint URL (among others).

We like to be as close and consistent with AWS as we can be, though sometimes we do need to deviate from their design principles due to the way plugins are designed. We're closely monitoring how they're thinking of implementing endpoint URLs beyond what they have today (the `--endpoint-url` CLI argument).

While using LocalStack, or other local AWS environments, do you ever have different endpoints per service, e.g., DynamoDB vs. S3 vs. EC2? Does LocalStack make all of these services available on the same endpoint? Also, do you ever use other local environments, like [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) together with LocalStack?

A per service endpoint only design does not seem like it'd work well with LocalStack, assuming that all AWS services are available on the same endpoint in LocalStack. 

Look forward to your thoughts on this!

**Comment by cbruno10** [comment]
Thanks @srgg for adding your suggestion, I like the idea of having a global endpoint URL with the ability to override per service.

In regards to the AWS plugin, I think following a similar design would be helpful, so here are my proposed ideas on custom endpoints:
- Add a config argument, `endpoint_url`, which is a global custom endpoint and can be set like `endpoint_url = "http://localhost:4566"`
- Add an environment variable, `AWS_ENDPOINT_URL`, which aligns with the proposed AWS environment variable and our config arg.
- As required, add service specific config args and environment variables, similar to what's in the [AWS proposal](https://github.com/kdaily/aws-sdk/blob/endpoint-url-configuration-proposal/proposals/configure-endpoint-url.md). I don't believe we need these yet, but we should watch when/how AWS implements these custom service endpoints and also prioritize adding them based on user requests.
- Order of precedence when evaluating which service endpoint URL to use:
  - Service specific config argument, e.g., `dynamodb_endpoint_url`, `s3_endpoint_url`
  - Service specific environment variable, e.g., `AWS_DYNAMODB_ENDPOINT_URL`, `AWS_S3_ENDPOINT_URL`
  - Global config argument, e.g., `endpoint_url`
  - Global environment variable, e.g., `AWS_ENDPOINT_URL`
  
 There are plans to move this plugin to use AWS Go SDK v2 as well, and I believe that SDK should support the above proposal as well per [Configuring Client Endpoints](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/).
 
 @srgg @johnsmyth - Any thoughts on the proposal above? Thanks!

**Comment by srgg** [comment]
@cbruno10 Proposed changes make a lot of sense to me. Moreover, I have updated PR that covers the following parts of the proposal you have made:

> * Add a config argument, `endpoint_url`, which is a global custom endpoint and can be set like `endpoint_url = "http://localhost:4566"`
> * Add an environment variable, `AWS_ENDPOINT_URL`, which aligns with the proposed AWS environment variable and our config arg.
> ....
> * Order of precedence when evaluating which service endpoint URL to use:
>   
>   * Global config argument, e.g., `endpoint_url`
>   * Global environment variable, e.g., `AWS_ENDPOINT_URL`

Can you please review [the PR](https://github.com/turbot/steampipe-plugin-aws/pull/105) one more time, and, hopefully, accept it?
