### ISSUE TITLE
Add table aws_rds_describe_pending_maintenance_actions

### ISSUE THREAD

**Issue by leandrotocachelis** [turbot/steampipe-plugin-aws#1060]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.
https://docs.aws.amazon.com/cli/latest/reference/rds/describe-pending-maintenance-actions.html
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribePendingMaintenanceActions.html
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html#USER_UpgradeDBInstance.Maintenance.Viewing

Important to know when maintenance will occur and why.

**Comment by cbruno10** [comment]
Hey @leandrotocachelis , thanks for raising this issue! As pending maintenance actions are always associated with a DB instance or DB cluster, we're planning on adding a new column, `pending_maintenance_actions`, to the existing DB instance and DB cluster tables. We'll also add some examples in the table docs for each of the tables in order to show how to query/use those columns.
