### ISSUE TITLE
Add table aws_macie2_findings and filters

### ISSUE THREAD

**Issue by tinder-tder** [turbot/steampipe-plugin-aws#1152]
A table to view Macie2 findings and filters would be useful for direct lookups of event details

**References**
https://docs.aws.amazon.com/sdk-for-go/api/service/macie2/#Macie2.ListFindings
https://docs.aws.amazon.com/sdk-for-go/api/service/macie2/#Macie2.ListFindingsFilters
https://docs.aws.amazon.com/sdk-for-go/api/service/macie2/#Macie2.GetFindings
https://docs.aws.amazon.com/sdk-for-go/api/service/macie2/#Macie2.GetFindingsFilter

**Comment by cbruno10** [comment]
Hey @tinder-tder , thanks for opening this request!

Based on the API details you sent over, I believe adding these tables should be fairly straight forward, with a note that adding in optional key qualifiers would be important, as there could be many findings and/or filters in a region.

If you're interested in trying to add these tables, we always appreciate any contributions to the plugin! For more information on our coding and documentation standards, please have a look at [Table and Column Standards](https://steampipe.io/docs/develop/standards) and [Table Documentation Standards](https://steampipe.io/docs/develop/table-docs-standards). If you have any questions about the development process otherwise, please let us know!
