### ISSUE TITLE
Add table aws_transit_gateway_connect

### ISSUE THREAD

**Issue by robinp-tw** [turbot/steampipe-plugin-aws#1180]
This is about "connect" attachments,  a special kind of attachment supported.
Currently the info we can find in steampipe is `aws_ec2_transit_gateway_vpc_attachment` table (which is not really only about vpc attachments) will have `resource_type = connect` and then the `transit_gateway_attachment_id` set to the attachment id.

But no further info about that attachment (and its connect peer) is present. For that we would need some new table.

**References**

https://docs.aws.amazon.com/vpc/latest/tgw/tgw-connect.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-transit-gateway-connect-peers.html
https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeTransitGatewayConnects
https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeTransitGatewayConnectPeers

Example results when running the aws cli describe commands:

```
{
    "TransitGatewayConnects": [
        {
            "TransitGatewayAttachmentId": "tgw-attach-xxxxx",
            "TransportTransitGatewayAttachmentId": "tgw-attach-yyyy",
            "TransitGatewayId": "tgw-zzzz",
            "State": "available",
            "CreationTime": ...,
            "Options": {
                "Protocol": "gre"
            },
            "Tags": ...
         }


{
    "TransitGatewayConnectPeers": [
        {
            "TransitGatewayAttachmentId": "tgw-attach-xxxxx",
            "TransitGatewayConnectPeerId": "tgw-connect-peer-wwwwwwwwwwww",
            "State": "available",
            "CreationTime": ...,
            "ConnectPeerConfiguration": {
                "TransitGatewayAddress": SOME_IP,
                "PeerAddress": OTHER_IP,
                "InsideCidrBlocks": [ ... ],
                "Protocol": "gre",
                "BgpConfigurations": [
                    {
                        "TransitGatewayAsn": SAME_ASN,
                        "PeerAsn": OTHER_ASN,
                        ...
                    },
                    {
                        ...
                    }
                ]
            },
            "Tags": ...
        }

```

Here `TransitGatewayAttachmentId` will be the tgw_id mentioned before. The interesting new info (for me) is:
- TransitGatewayConnectPeerId
- ConnectPeerConfiguration.BgpConfigurations.PeerAsn
- maybe some of the IP addresses within

which will let me identify which connect peer an attachment leads to (the same physical connect peer will have different connect_peer_ids, so the IPs/ASN seems required to make the correlation).

Note: in the mean time resolving the `resource_id` from the `aws_ec2_transit_gateway_vpc_attachment` table to the `vpc` that hosts the connect peer is an ok-ish workaround, but a single VPC can host multiple connect peers, so more details would be nice.

cc @ranjeetkumar191

**Comment by cbruno10** [comment]
Hey @robinp-tw, thanks for creating this request (and including so much detail)!

I see a few new potential tables based on your notes and the docs you sent over:
- `aws_transit_gateway_connect`
- `aws_transit_gateway_connect_peer`

It seems like they're better off functioning as two separate tables, instead of putting the connect or connect peer info inside another table's columns, but based on the data returned, there may be another way. Would you expect them to be their own separate tables?

Also, the SDK docs you linked have a lot of good info and the list/get APIs for connects and connect peers seem fairly easy to work with.

If anyone is interested in trying to add these tables, we're always excited to see new PRs coming in! For more information on our coding and documentation standards, please have a look at [Table and Column Standards](https://steampipe.io/docs/develop/standards) and [Table Documentation Standards](https://steampipe.io/docs/develop/table-docs-standards). If you have any questions about the development process otherwise, please let us know!
