### ISSUE TITLE
GovCloud Lambda Permission issue

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe-plugin-aws#1262]
**Describe the bug**
Querying Lamba Tables from GovCloud regions results in AccessDenied errors

**Steampipe version (`steampipe -v`)**
Example: v0.6.0

**Plugin version (`steampipe plugin list`)**
Example: v0.74.1

**To reproduce**
Login to a gov cloud region with lambda functions.
select * from aws_lambda_function;
select * from aws_lambda_alias;

**Expected behavior**
Results return without error.

**Additional context**
the role I am using has AdministratorAccess
I believe it is an issue with the column `url_config` possibly trying to do a cross aws partition lookup?

<img width="1176" alt="lambda_error" src="https://user-images.githubusercontent.com/54130/186937195-c6e501ae-3eda-4274-ac76-bfe00f133cfe.png">

**Comment by cbruno10** [comment]
Hey @dboeke , thanks for the report! It does look like the `url_config` column is the main one causing issues, probably due to function URLs being unavailable in GovCloud as per [How AWS Lambda Differs for AWS GovCloud (US)
](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-lambda.html#govcloud-lambda-diffs).

We'll look to release a fix this week, thanks!
