### ISSUE TITLE
Add table aws_resource_explorer

### ISSUE THREAD

**Issue by wesky93** [turbot/steampipe-plugin-aws#1386]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

[supported resources ](https://docs.aws.amazon.com/resource-explorer/latest/userguide/supported-resource-types.html?icmp=docs_re_console_supported-resource-types)

Related Go Library Method: (https://docs.aws.amazon.com/sdk-for-go/api/service/resourceexplorer2/
)

Note: I think this table can be used as an index table for simple resource search. So, when signing using a name, faster queries are possible to query faster than before.

**Comment by misraved** [comment]
Welcome to Steampipe @wesky93 👍 and thanks for raising the request 👍 .

If anyone would like to attempt to develop this table, the API mentioned by @wesky93  is an excellent place to start.

Please let us know in case there are questions 👍 .

**Comment by cbruno10** [comment]
Looking a bit more at the service and [Resource Explorer API](https://docs.aws.amazon.com/resource-explorer/latest/apireference/API_Operations.html), here are some initial thoughts:

There appear to be a few different resource types from the get and list methods:
- Index (has an ARN, supports tags)
- Supported resource type (no individual ARN, but contains info on resource type + service)
- View (has an ARN, supports tags)

There’s also a [Search method](https://docs.aws.amazon.com/resource-explorer/latest/apireference/API_Search.html), and you need to give a view ARN as part of the request.

Someone had created an issue in the TF AWS provider as well with some initial resource and data source ideas - https://github.com/turbot/steampipe-plugin-aws/issues/1386

Looking at the list/get methods above, the proposed tables are:
- `aws_resource_explorer_index`
- `aws_resource_explorer_search` (good example queries will be important so users know how to use the query string param)
- `aws_resource_explorer_supported_resource_type`
- `aws_resource_explorer_view`

**Comment by cbruno10** [comment]
The service in the AWS CLI and Go SDK docs is called Resource Explorer 2. I'm not sure what happened to Resource Explorer 1, but I think it's better to drop the `2` in the table names, since there is no Resource Explorer 1 service.

**Comment by jchrisfarris** [comment]
search is the most useful API in this. The others really just seem to be related to enabling the service. If a view isn't passed as a qual to the search function, I'd use [GetDefaultView](https://docs.aws.amazon.com/goto/WebAPI/resource-explorer-2-2022-07-28/GetDefaultView) to populate that. 

How would their [query syntax](https://docs.aws.amazon.com/resource-explorer/latest/userguide/using-search-query-syntax.html) get translated into SQL? 

Do we create WHERE clauses like ` where service='ec2' and regions='us-west-2' ` and map that to `service:EC2 region:us-west-2` in their language? or does the where clause pass the resource explorer query straight through?

**Comment by cbruno10** [comment]
@jchrisfarris Thanks for sharing the `GetDefaultView` API, I agree that it'd be helpful to use that if no view ARN is passed in for the `aws_resource_explorer_search` table.

For the query syntax, I think we'd start with having a `query` column that we'd pass directly in, like the [github_search_code](https://hub.steampipe.io/plugins/turbot/github/tables/github_search_code) table (and other `github_search_*` tables) handle it.

This usually works well for inputs with specific query languages because:
- If a user creates their own queries today for use with the API/SDK/CLI, they can re-use them here (and vice versa)
- There's usually sufficient documentation from the provider on how to form a query
- We don't need to create our own column -> query string handling, which can be complex depending on the query language
