### ISSUE TITLE
Cannot query multiple AWS connections

### ISSUE THREAD

**Issue by volphy** [turbot/steampipe-plugin-aws#1404]
**Describe the bug**
I have local configuration with three AWS connections specified. Each connection refers to one AWS profile. Each AWS profile contains STS credentials.

Querying anything using the first AWS connection works. Querying anything using second and third AWS connection fails.

**Steampipe version (`steampipe -v`)**
v0.17.2

**Plugin version (`steampipe plugin list`)**
aws - v0.83.0
awscfn - v0.2.0
steampipe - v0.6.0

**To reproduce**
Create 3 AWS profiles in ~/.aws/credentials:

```
[staging]
aws_access_key_id=...
aws_secret_access_key=...
aws_session_token=...

[preprod-cp]
aws_access_key_id=...
aws_secret_access_key=...
aws_session_token=...

[prod-cp]
aws_access_key_id=...
aws_secret_access_key=...
aws_session_token=...
```

Create 3 AWS connections in the Steampipe configuration:

~/.steampipe/config/steampipe.spc:
```
connection "steampipe" {
  plugin = "steampipe"
}
```

~/.steampipe/config/aws.spc:
```
connection "aws_staging" {
  plugin  = "aws"
  profile = "staging"
  regions = ["eu-west-1"]
}

connection "aws_preprod_cp" {
  plugin  = "aws"
  profile = "preprod_cp"
  regions = ["eu-west-1"]
}

connection "aws_prod_cp" {
  plugin  = "aws"
  profile = "prod_cp"
  regions = ["eu-west-1"]
}
```

Run the following query on the first connection:
```
steampipe query
> select * from aws_staging.aws_s3_bucket
5 rows returned
```

Run the following query on the second connection:
```
> select * from aws_preprod_cp.aws_s3_bucket
Error: rpc error: code = DeadlineExceeded desc = operation error S3: ListBuckets, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded (SQLSTATE HV000)
0 rows returned
...
```

Run the following query on the third connection:
```
> select * from aws_prod_cp.aws_s3_bucket
Error: rpc error: code = DeadlineExceeded desc = operation error S3: ListBuckets, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded (SQLSTATE HV000)
0 rows returned
...
```

**Expected behavior**
Each query should return several rows.

**Comment by e-gineer** [comment]
Hi @volphy ... Looking at the config, it appears that your profiles are called `preprod-cp` (with ` -`) while the connection defines them as `profile = "preprod_cp"` (with a `_`).

Because it cannot find the profile, we are falling back to the default connection on the machine (assumedly looking for an EC2 role via IDMS).

I'm not sure if we can improve this error message (it's confusing), but I believe the root cause is the misconfiguration above. Can you try fixing that?

**Comment by volphy** [comment]
@e-gineer 
Thanks a lot.

After fixing my aws.spc file steampipe query works really well.

It would be great  to improve this error message.

Thinking further, would it be possible to add configuration validation to steampipe i.e.,
```
steampipe validate
```
?

Steampipe validation command could either:
- perform static validation a la CloudFormation validation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/validate-template.html
- perform static & dynamic validation: the same as above plus verification whether connections (here: AWS connections) can be established successfully

**Comment by misraved** [comment]
Great to see that your issue got resolved @volphy 👍. I do not think we can improve the error message here since it is returned by the underlying API.

`steampipe validate` seems like an interesting approach to checking the configuration file (`.spc`) prior to query execution.

Our plugins do have a good mechanism today to check if the credentials/configuration required to make the API calls are missing or not, but we don't seem to weed out the errors in the event of misconfiguration or typos.

Leading on the `steampipe validate` command, I think it's a great suggestion. Could you please open an issue in the https://github.com/turbot/steampipe/issues repository to initiate the discussion with @kaidaguerre, @e-gineer, and @johnsmyth 👍?

Once again thanks for using Steampipe and please let us know if you run into any issues 👍. Happy to help!!
