### ISSUE TITLE
aws_s3_bucket should use HeadBucket instead of GetBucketLocation

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#1586]
From https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html:

> For requests made using AWS Signature Version 4 (SigV4), we recommend that you use [HeadBucket](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) to return the bucket Region instead of GetBucketLocation.

https://github.com/turbot/steampipe-plugin-aws/blob/6418b0bf93cd67ad753cca67168fd0fe1a4ff082/aws/table_aws_s3_bucket.go#L338-L342

**Comment by pdecat** [comment]
Can't you see what the `location` header was set to in the 301 response?

**Comment by Veetaha** [comment]
Using HeadBucket instead makes sense, because `GetBucketLocation` can return a special string `EU`. See it specified in the API docs of this method:
![image](https://github.com/turbot/steampipe-plugin-aws/assets/36276403/e355f2d7-9560-40bf-be53-45397e0d7b83)

There is no such region as "EU", so steampipe AWS plugin right now has this crutch:
https://github.com/turbot/steampipe-plugin-aws/blob/b71914ee85a7816fc5cc6eaf65be61f344a0a21d/aws/table_aws_s3_bucket.go#L422-L429

I'm not sure how correct this is. I couldn't find any docs that actually say that `EU == eu-west-1`, but it looks like it practically is?

**Comment by pdecat** [comment]
> I'm not sure how correct this is. I couldn't find any docs that actually say that `EU == eu-west-1`, but it looks like it practically is?

It sort of does https://github.com/EverythingMe/ncdu-s3/pull/4 🙂

**Comment by Veetaha** [comment]
> making simple unauthenticated requests is enough to get the desired header

That is surprising... Also, I'm not sure how much quota AWS provides for the rate of unauthenticated requests. It's probably lower? And the question is wether the response still contains the bucket region if a RateExceeded or Throttling error is returned

**Comment by pdecat** [comment]
There's caching in the steampipe query data connection manager to avoid requesting the region to often for a single bucket. I've not faced throttling on that HEAD method yet, will perform more load testing ASAP to see how it behaves.

FWIW, I'm almost done before submitting my PR.

**Comment by vpartington** [comment]
FYI, instead of using `http.Head` you can also use [the `manager.GetBucketRegion` function](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/s3/manager#GetBucketRegion) in AWS SDK for Go v2.
