### ISSUE TITLE
Does aws_route53_domain work with default regions outside us-east-1 and non-commercial partitions?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-aws#1587]
Looking at the code, we assume the default region in each partition, which seems unlikely to work?

https://github.com/turbot/steampipe-plugin-aws/blob/a8d5bde9c9f20ab30d7a57ad9983d272f5e47ad0/aws/service.go#L1038-L1044

**Comment by ParthaI** [comment]
@e-gineer, Apologize for the late response. I was taking a look into it. Providing my observation below please have a look, Thanks!

- I created 2 separate connections(Commercial and Non-commercial)
- For commercial connection with single region(rather than us-east-1) and with region `*` seems to be working fine.
- For non commercial region with single region and with region `us-gov-*` the query keeps loading.

As AWS Route53 Domain is a global service, we are using the [getClientForLastResortRegion](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/service.go#L1117) function for creating a client with an endpoint. 

Also I have tried by changing it to `getClientForDefaultRegion` for creating the client, the query behaviour is same as the above.

**Query:**
`select * from aws_route53_domain` and `select * from aws_gov.aws_route53_domain`

**Commercial Connection:**
```
connection "aws" {
  plugin = "aws"
  regions = ["us-east-2"]
  profile = "aws_nagraj"
}
```

**Non-Commercial Connection:**
```
connection "aws_gov" {
  plugin  = "aws"
  regions = ["us-gov-*"]
  profile = "aws-gov-deadshot"
}
```
