### ISSUE TITLE
Add tables for inspector2 findings

### ISSUE THREAD

**Issue by seanthebear** [turbot/steampipe-plugin-aws#1643]
Unable to get results from inspector queries when using inspector2. Need tables created so I can run queries against number of vulnerabilities detected that are High, Medium and informational as well as id, arn, asset type and numerical severity for a start.

**Comment by jaredreisinger-drizly** [comment]
Serendipitously, I started working on adding (some) inspector2 tables last week, `findings` and `coverage` among them.

@cbruno10, @misraved: I have some questions about best practices and the like; is this an acceptable place to ask them?  For example, is it okay to just add a few of the inspector2 tables (the ones I need) rather than attempting to flesh out the entire set of 10 (based on the `aws inspector2 list-*` CLI commands)?  Also, `inspector2` is a little different from most services in that you can query one account, and get results back from more than one account... so the `account_id` behavior may be somewhat different from most resources.  I want to make sure that I get it right, so that folks aren't surprised by the results.  Some `inspector2` CLI calls use `awsAccountId` to differentiate, but some do not, and I'm not sure about how closely to the AWS CLI I should stay, vs. having a more-consistent experience within steampipe.

**Comment by cbruno10** [comment]
@jaredreisinger-drizly Awesome, we're happy to hear you started working on them 😄 

Yes, it's definitely OK to add some tables from a service initially. You'll find that for a lot of services we have tables for, we don't have all of the possible tables implemented yet.

I'm not deeply familiar with Inspector2 API results, but my suggestion would be to keep the `account_id` (which is a common column across all tables) as the account that the API request is being made against. If there's another field that the Inspector2 API returns specifically to represent which AWS account the finding/other resource is from, we can always add that field with an altered column name, e.g, `finding_account_id`. For instance, in many tables, we represent the `Tags` property as `tags_src` (https://github.com/turbot/steampipe-plugin-aws/blob/33ba2d0f6e1300912cca877b12d3a36fb8ff355d/aws/table_aws_ebs_volume.go#L138-L143).

If you have any other questions, please let us know!

**Comment by jaredreisinger-drizly** [comment]
Thank you so much for the quick response!

One other (hopefully quick and easy) question: In some cases, the returned value includes a nested structure, not a list of them, but just a nested object that hold several related fields.  This makes 100% sense in a JSON world, but isn't as useful in SQL/tables.  My current plan is to flatten these into columns, for example, to make:

```javascript
{
  // ...
  scanStatus: {
    reason: "whatever",
    statusCode: "whatever",
  },
  // ...
}
```

into two columns, `scan_status_reason` and `scan_status_code`, omitting the `scanStatus` object itself.  This also helps because AWS allows filtering by those fields, and writing `where scan_status_code = 'whatever'` feels like very natural SQL.

Let me know if that _isn't_ the recommended way to deal with simple nested structures.  😄

**Comment by cbruno10** [comment]
@jaredreisinger-drizly Sorry I missed your latest question until now! In these situations, if we do decide to add top level column support to nested properties, we'll usually keep the original column, e.g., `scan_status`, but then potentially add more top level columns.

We add columns instead of replacing to preserve the data we get from AWS, so it looks familiar to what users would see when using other SDKs or the AWS CLI.

In terms of how to decide if additional columns should be added, I've included some criteria we use when making similar decisions:
- How key are the properties to the table? For instance, do most examples use these properties? If so, this may be good reason to add them as top level columns too.
- How nested are the properties? One level nesting isn't usually too bad, but if there are 2+ levels, that can be difficult to query.
- Would you be able to use these columns as key columns?

In this case, based on the questions above and the info you provided, I think it'd make sense to add 2 additional columns, `scan_status_reason` and `scan_status_status_code`. The `scan_status_status_code` column name is a bit long and redundant, but following this naming convention makes naming decisions more consistent across all plugins.

Hope that helps!

**Comment by ParthaI** [comment]
Added the tables in [this PR](https://github.com/turbot/steampipe-plugin-aws/pull/1736)
