### ISSUE TITLE
Consistency and completeness of AWS tables and objects

### ISSUE THREAD

**Issue by foolioo** [turbot/steampipe-plugin-aws#1712]
**Is your feature request related to a problem? Please describe.**

Steampipe is awesome, it provides a great interface to query AWS resources - something which neither [AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html), not [AWS Resource Explorer](https://docs.aws.amazon.com/resource-explorer/latest/userguide/welcome.html) give.

While using Steampipe, we found out that:
1. Some properties are missing from AWS tables
2. There is no table naming convention that coincide with AWS SDK names. E.g. `aws ec2` CLI command is reflect in Steampipe as `aws_ec2_instance`

**Describe the solution you'd like**

With respect to the numbers above:
1. Implement a mechanism to detect what is missing, add the missing properties and object and repeat the process to guarantee consistency and completeness of Steampipe tables data
2. Document how AWS objects are being translated into Streampipe tables and objects and implement such a naming\translation convention if it is missing

**Describe alternatives you've considered**

With respect to the numbers above:
1. Query Steampipe tables names and table schemas and compare them with [Boto data-structure](https://github.com/boto/botocore/tree/develop/botocore/data)
2. Query Steampipe tables and intelligent guess what is the corresponding table and column that should be use to retrieve specific property

**Additional context**

- [Boto API client reference](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html#api-reference)
- https://github.com/turbot/steampipe-plugin-aws/issues/1708
- https://github.com/turbot/steampipe/discussions/3355

**Comment by cbruno10** [comment]
Hey @foolioo , thanks for opening this issue!

We agree that ensuring we're up to date with all properties is a challenge today, and something we don't always keep up to date with in this plugin (and others). I like the idea of adding a mechanism to detect what's missing across the tables. Instead of boto, since we use the [AWS SDK Go v2](https://github.com/aws/aws-sdk-go-v2), we could look to compare our columns against the types in that package, e.g., for `aws_acm_certificate`, look at the [CertificateDetail type](https://github.com/aws/aws-sdk-go-v2/blob/main/service/acm/types/types.go#L12).

It wouldn't always be a 1:1 mapping, since for many tables, we pull in API data from other APIs as part of our hydrate calls, e.g., tables like `aws_s3_bucket` can have 10+ additional API calls.

Another approach we've considered is to look at AWS API changes, like those from https://awsapichanges.info/, and try to recognize changes that'd affect our tables, but this also has its own challenges.

For the table naming convention, we generally follow the convention of `aws_<service>_<resource>`, e.g., `aws_s3_bucket`, `aws_ec2_instance`, `aws_dax_parameter_group`. For the resource name, we generally look at the API/CLI resource name and follow that. There are more details on table naming conventions in https://steampipe.io/docs/develop/standards#naming.

For table names, did you find any that you found inconsistent, or were surprised that they were named that way?

**Comment by cbruno10** [comment]
@foolioo We don't have any active ongoing work for automating detection/remediation of missing columns at the moment, but if you have any other thoughts or suggestions around it we're still interested in discussing it, as we'd like to implement it one day.

And I don't believe that familiarity with the AWS CLI/SDK doesn't have any benefit when querying Steampipe. The service and resource names mentioned in the commands, like `aws ec2 describe-instances`, are used in our table names, like `aws_ec2_instance`. The reason we don't have a 1:1 mapping for some tables is that often AWS has broken out information about a single resource type across multiple types. For instance, `aws ec2 describe-instances` has a lot of information about EC2 instances, but if you want to get kernel data, user data, or root instance data, you'd need to use `aws ec2 describe-instance-attribute --attribute <attribute here>`.

So in terms of service resources, we often have 1 table mapping to each service resource, but for information about each resource, we may pull from multiple APIs for ease of use.

**Comment by bigdatasourav** [comment]
Hey @foolioo, we are closing this issue for now; Please feel free to reopen the issue if you want to share or discuss anything.
