### ISSUE TITLE
Add table aws_ec2_launch_template_version

### ISSUE THREAD

**Issue by shaul75** [turbot/steampipe-plugin-aws#1724]
**Is your feature request related to a problem? Please describe.**

The AWS plugin lacks the possibility to query for _aws_ec2_launch_template_version_.
I'd like to query for all $Default LTs and display the LT name, version and AMI associated with it.
The only way now seems to be querying aws_ec2_instance.launch_template_data -> 'ImageId', but it somewhat complicates things imo.

**Describe the solution you'd like**

_aws_ec2_launch_template_version_ - the equivalent of `aws ec2 describe-launch-template-versions`

**Comment by rajlearner17** [comment]
@shaul75 Appreciate using Steampipe! Thanks for raising the table request!!. 
We have moved the issue here to the AWS plugin repo. 

Thanks for the information provided; while we look into it, can you please provide your use case and how you use Steampipe, particularly this aws_ec2_launch_template feature? This will help us.
