### ISSUE TITLE
Add subscriptions to table `aws_sns_topic`

### ISSUE THREAD

**Issue by JohannesKonings** [turbot/steampipe-plugin-aws#1817]
Table `aws_sns_topic` doesn't contain the list of subscriptions
https://hub.steampipe.io/plugins/turbot/aws/tables/aws_sns_topic

Here is the API reference
https://docs.aws.amazon.com/sns/latest/api/API_ListSubscriptionsByTopic.html

**Comment by cbruno10** [comment]
Hey @JohannesKonings , we currently allow you to list SNS topic subscriptions with the [aws_sns_topic_subscription](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_sns_topic_subscription). Does this table provide you the information you're looking for?

**Comment by JohannesKonings** [comment]
I think [aws_sns_topic_subscription](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_sns_topic_subscription) is this API : https://docs.aws.amazon.com/sns/latest/api/API_ListSubscriptions.html
These are the subscriptions of "my" account.
I like to have the subscriptions of the SNS topics of from my account to check who uses my SNS topics.

Thank you

**Comment by cbruno10** [comment]
@JohannesKonings We actually have been discussing this issue a bit in https://github.com/turbot/steampipe-plugin-aws/issues/1488, and I think if we can find a resolution in that issue, that should address the issue here too.

In that issue, I also suggested a [workaround](https://github.com/turbot/steampipe-plugin-aws/issues/1488#issuecomment-1352190751) using another AWS connection you can try in the meantime.

I'm closing this issue and will re-open https://github.com/turbot/steampipe-plugin-aws/issues/1488 (closed due to inactivity). If you have any other info or questions, feel free to add them into the linked issue.
