### ISSUE TITLE
Add table aws_lambda_event_source_mapping

### ISSUE THREAD

**Issue by nickman** [turbot/steampipe-plugin-aws#1872]
Proposing a new table `aws_lambda_event_source_mapping` which supports the Event Source Mapping Configurations which associate event sources to each Lambda Function. Preparing a PR for this.

**References**

- [EventSourceMappingConfiguration](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda@v1.39.2/types#EventSourceMappingConfiguration)
- [Client.GetEventSourceMapping](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda#Client.GetEventSourceMapping)
- [GetEventSourceMappingInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda#GetEventSourceMappingInput)
- [GetEventSourceMappingOutput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda#GetEventSourceMappingOutput)

Work in progress:

![steampipe - per - aws_lambda_event_source_mapping](https://github.com/turbot/steampipe-plugin-aws/assets/597608/bf5d221c-d489-4bba-9ea2-437cdd9b287a)

**Comment by cbruno10** [comment]
Hey @nickman , thanks for starting a PR on this!

For listing event sources, I believe you need to this pass a Lambda function name in the API call. If this is true, I'd recommend trying out a `ParentHydrate`, like in [this](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_lambda_alias.go#L34) table, so you don't have to list functions yourselves. For getting a specific event sources mapping, I believe you just need the event source's UUID.

Also, for table name, I'd recommend going with `aws_lambda_event_source_mapping`, since we usually use the AWS API resource names as table names, since those are used consistently throughout AWS SDK's, CLI, console, etc.

If you have any questions please let us know!

**Comment by nickman** [comment]
Added all remaining JSONB columns.

![image](https://github.com/turbot/steampipe-plugin-aws/assets/597608/85545ff6-14b7-4f97-9a42-f08fd02fbaea)

**Comment by nickman** [comment]
Example Row:

```
{
"SELECT *\nFROM per.aws_lambda_event_source_mapping\n": [
	{
		"uuid" : "a9156ea4-3229-491c-b829-0dcbeec86702",
		"event_source_arn" : "arn:aws:kinesis:us-east-1:XXXXXXXXX:stream\/ref.instruments",
		"function_arn" : "arn:aws:lambda:us-east-1:XXXXXXXXX:function:eventaudit",
		"function_name" : "eventaudit",
		"service_name" : "kinesis",
		"service_component_name" : "ref.instruments",
		"service_component_type" : "stream",
		"batch_size" : 100,
		"bisect_batch_on_function_error" : true,
		"last_modified" : "2022-09-24T20:22:00.000Z",
		"last_processing_result" : "OK",
		"maximum_batching_window_in_seconds" : 10,
		"maximum_record_age_in_seconds" : -1,
		"maximum_retry_attempts" : -1,
		"parallelization_factor" : 10,
		"state" : "Enabled",
		"state_transition_reason" : "User action",
		"tumbling_window_in_seconds" : 0,
		"function_response_types" : "[]",
		"source_access_configurations" : null,
		"destination_config" : "{\"OnFailure\": {\"Destination\": null}, \"OnSuccess\": null}",
		"filter_criteria" : null,
		"amazon_managed_kafka_event_source_config" : null,
		"queues" : null,
		"scaling_config" : null,
		"self_managed_event_source" : null,
		"self_managed_kafka_event_source_config" : null,
		"starting_position" : "LATEST",
		"starting_position_timestamp" : null,
		"topics" : null,
		"partition" : "aws",
		"region" : "us-east-1",
		"account_id" : "XXXXXXXXX",
		"_ctx" : "{\"connection_name\": \"per\"}"
	}
]}
```

**Comment by bigdatasourav** [comment]
[PR](https://github.com/turbot/steampipe-plugin-aws/issues/1872) is under review.
