### ISSUE TITLE
Add table aws_cloudtrail_lookup_event

### ISSUE THREAD

**Issue by ksmaheshkumar** [turbot/steampipe-plugin-aws#1902]
**References**

The existing table aws_cloudtrail_trail_event is fetching from CLOUDWatch instead / additionally we can fecth from Cloud trail events.

Reference
https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_LookupEvents.html

**Comment by cbruno10** [comment]
We already have a table called `aws_cloudtrail_trail_event`, which I think this new table would be ideally named. We could add functionality to the existing `aws_cloudtrail_trail_event` table, so that if a log group name were not given, it'd get results directly from CloudTrail (though throttling is heavy, I think 2 requests/second for LookupEvents), so it could take a while to get the last 2 weeks worth of events in a busy account.

Alternatively, we could create a new table, e.g., `aws_cloudtrail_lookup_event`, like suggested in the issue title, or another name, but I'm not sure what I'd call it.

We follow a similar pattern in `table_aws_vpc_flow_log_event` as well.

**Comment by ksmaheshkumar** [comment]
Cloudtrail to Cloudwatch not followed in all places due to log ingestion, storage and querying costs.

**Comment by ksmaheshkumar** [comment]
Commenting for keeping it alive

**Comment by StephenKing** [comment]
Should not be closed IMHO
