### ISSUE TITLE
aws_cloudwatch_log_group key column is not globally unique

### ISSUE THREAD

**Issue by bryanburke** [turbot/steampipe-plugin-aws#1975]
**Describe the bug**

The key column for the aws_cloudwatch_log_group table is `name`: <https://github.com/turbot/steampipe-plugin-aws/blob/v0.123.0/aws/table_aws_cloudwatch_log_group.go#L23>

However, Amazon CloudWatch Logs log group names are only unique within a specific AWS account and region. Thus, queries that filter on exact log group name fail when the same log group name exists in multiple account-region pairs.

I believe the solution is to make the globally unique resource ARN the key column for the table.

Other CloudWatch Logs resource tables may be affected as well, though I have not tested them. For example: <https://github.com/turbot/steampipe-plugin-aws/blob/v0.123.0/aws/table_aws_cloudwatch_log_stream.go#L29>

**Steampipe version (`steampipe -v`)**

v0.21.0

**Plugin version (`steampipe plugin list`)**

v0.123.0

**To reproduce**

1. Create a CloudWatch Logs log group named "steampipe-test" in us-east-1.
1. Create another log group named "steampipe-test" in us-east-2 in the same AWS account.
1. Query log groups across both regions with a filter on that exact name:

   ```sh
   steampipe query  "SELECT account_id, region, name FROM aws_cloudwatch_log_group WHERE name = 'steampipe-test' ORDER BY account_id ASC, region ASC;"
   ```

1. Observe the following error: `Error: get call returned 2 results - the key column is not globally unique (SQLSTATE HV000)`

**Expected behavior**

The query above no longer results in an error.

**Additional context**

Until this issue is fixed, using `LIKE` instead of exact equality seems to be a workaround:

```sh
steampipe query  "SELECT account_id, region, name FROM aws_cloudwatch_log_group WHERE name LIKE 'steampipe-test' ORDER BY account_id ASC, region ASC;"
```

However, in terms of execution plan, I imagine `LIKE` is less efficient than exact string matching.

Thanks for all your hard work making and supporting this wonderful tool!

**Comment by ParthaI** [comment]
@bryanburke, I'm sorry to hear that you're experiencing issues.

- Upon initial inspection, it appears that our plugin code uses the `DescribeLogGroups` API to filter results by name.

- The name value provided in the query parameter serves as the input for the `DescribeLogGroups` API, with the value being passed as `[LogGroupNamePrefix](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_cloudwatch_log_group.go#L193)`.

- Since AWS CloudWatch Log Groups are regional resources, the API is designed to be called once for each region configured in the `aws.spc` file.

- We have configured this API call in the [GetConfig](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_cloudwatch_log_group.go#L22) section of this table.

- From a Steampipe design perspective, the GetConfig function should ideally return a single row and not more than one, which is causing the issue.

We will take a look at the issue.

Thanks!
