### ISSUE TITLE
Add table aws_iot_*

### ISSUE THREAD

**Issue by jolo-dev** [turbot/steampipe-plugin-aws#1994]
Add new tables (plural!!)
- `aws_iot_core_things`
- `aws_iot_core_thing_groups`
- `aws_iot_core_thing_types`
- `aws_iot_core_fleet_metrics`
- `aws_iot_greengrass_devices`
- `aws_iot_greengrass_components`
- `aws_iot_greengrass_deployments`
- `aws_iot_greengrass_devices`
- `aws_iot_greengrass_groups`

**References**
[AWS IoT Core](https://aws.amazon.com/iot-core/?nc=sn&loc=2&dn=3)
[AWS IoT Greengrass](https://aws.amazon.com/greengrass/?nc=sn&loc=2&dn=2)

**Comment by ParthaI** [comment]
@jolo-dev, I have raised the PR for the tables `aws_iot_thing`, `aws_iot_thing_type`, `aws_iot_thing_group`, `aws_iot_greengrass_component`, `aws_iot_greengrass_core_device`, and `aws_iot_greengrass_deployment`. It would be great if you could give it a try and share your feedback with us.

- For querying the tables `aws_iot_thing`, `aws_iot_thing_type`, and `aws_iot_thing_group`, we need to merge the pr branches(`issue-1994`, `add-table-iot-thing-type`, and `add-table-iot-thing-group`) into a single branch, because there is a dependency between the PRs.
- For querying the tables `aws_iot_greengrass_*` you can use the branch `add-table-iot-greegrass`.

Steps for testing out the tables:
- git clone https://github.com/turbot/steampipe-plugin-aws.git
- cd `steampipe-plugin-aws`
- git checkout add-table-iot-greegrass if you want to test the `aws_iot_greengrass_*` tables and create a separate branch(`git checkout -b my-test-branch`) and pull the code changes from the branches `issue-1994`, `add-table-iot-thing-type`, and `add-table-iot-thing-group`.
- make
- Run the Query

Thanks!

**Comment by jolo-dev** [comment]
Oh, I totally forgot about that.
