### ISSUE TITLE
Add table aws_rds_db_recommendation

### ISSUE THREAD

**Issue by captainfalcon23** [turbot/steampipe-plugin-aws#2050]
**References**

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-recommendations.html

Kindly implement a table which references this AWS CLI action (and associated web API).

**Comment by ParthaI** [comment]
Hello @captainfalcon23, thank you for bringing this issue to our attention. Your engagement with Steampipe is greatly valued. I will take a look into it.

**Comment by captainfalcon23** [comment]
Not stale

**Comment by ParthaI** [comment]
Hello, @captainfalcon23, apologies for the delayed response on this matter.

We are currently utilizing the AWS RDS Go package version [v1.40.1](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds@v1.40.1), which unfortunately does not include support for the [DescribeDBRecommendations](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBRecommendations.html) API.

Support for this API was introduced in version [v1.65.0](https://github.com/aws/aws-sdk-go-v2/blob/main/service/rds/CHANGELOG.md#v1650-2023-12-19). However, it's important to note that there have been breaking changes since version [v1.49.0](https://github.com/aws/aws-sdk-go-v2/blob/main/service/rds/CHANGELOG.md#v1490-2023-07-31).

Our next step is to upgrade our plugin to utilize the latest version of the AWS Go SDK. After that, we'll revisit this issue.

Thanks for your understanding and patience!

**Comment by captainfalcon23** [comment]
All good @ParthaI, hopefully it gets revisited/reopened once that work is done.

**Comment by captainfalcon23** [comment]
Hi @ParthaI 
Just revisiting this issue (unsure why it got closed). I see now the following is being used:
	github.com/aws/aws-sdk-go-v2/service/rds v1.77.0

Would the team be able to revisit this request?

**Comment by ParthaI** [comment]
Sorry, @captainfalcon23, I missed to reopen this issue. Yes, the supported version of the RDS package for the [DescribeDBRecommendations](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBRecommendations.html) API is included in our current main branch.

The issue has been reopened. I will take a look. Thank you!
