### ISSUE TITLE
Interface Conversion Error When Querying aws.aws_health_affected_entity

### ISSUE THREAD

**Issue by dalenewman** [turbot/steampipe-plugin-aws#2069]
**Describe the bug**
When I run a query on the `aws.aws_health_affected_entity` table, I get this error below.  It happens when there are events present (there are records returned from `aws.aws_health_event`), otherwise it returns 0 records.

```
ERROR: rpc error: code = Unknown desc = aws: interface conversion: interface {} is types.Event, not *types.Event
```

**Steampipe version (`steampipe -v`)**
v0.21.4

**Plugin version (`steampipe plugin list`)**
0.130.0

**To reproduce**
Run `select * from aws.aws_health_affected_entity` when `select * from aws.aws_health_event` returns results/events.

**Expected behavior**
It should return results instead of throwing the error mentioned above.

**Additional context**
I am querying AWS accounts that are in a gov-cloud region.

**Comment by ParthaI** [comment]
Hello @dalenewman, We have raised a [draft PR](https://github.com/turbot/steampipe-plugin-aws/pull/2072) addressing this issue (but difficult to test since we don't have direct access to the API in our accounts).

We would appreciate it if you could test the changes in the PR branch and share your feedback with us.

Instructions for testing the code changes in the pull request branch:
1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-aws.git`
2. Navigate into the repository directory: `cd steampipe-plugin-aws`
3. Switch to the branch `issue-2069`: `git checkout issue-2069`
4. Execute the `make` command.
5. Execute the query.

Thank you!

**Comment by dalenewman** [comment]
Yes it works. Thank you. 👌

---
![image](https://github.com/turbot/steampipe-plugin-aws/assets/933086/3c638a0a-b424-4115-8cbd-90e6dc85b9e3)
