### ISSUE TITLE
aws_ec2_network_interface_ panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by blurayne** [turbot/steampipe-plugin-aws#2095]
```
> SELECT array_agg(network_interface_id) eni_ids, array_agg(DISTINCT description) desc,  array_agg(DISTINCT attached_instance_id) instance_ids, COUNT(attached_instance_id) FROM aws_ec2_network_interface WHERE attached_instance_id IS NULL  GROUP BY attached_instance_id
panic: interface conversion: interface {} is nil, not string

goroutine 42 [running]:
github.com/turbot/steampipe/pkg/db/db_client.populateRow.func1(...)
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:324
github.com/turbot/steampipe/pkg/utils.Map[...](...)
	/home/runner/work/steampipe/steampipe/pkg/utils/collection.go:41
github.com/turbot/steampipe/pkg/db/db_client.populateRow({0xc000a327c0, 0x4, 0x409f1e?}, {0xc00074a0c0, 0x4, 0x0?})
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:324 +0x11bd
github.com/turbot/steampipe/pkg/db/db_client.readRow({0x25e9190?, 0xc0016ff9e0?}, {0xc00074a0c0, 0x4, 0x4})
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:313 +0x6c
github.com/turbot/steampipe/pkg/db/db_client.(*DbClient).readRows(0x0?, {0x25dfb18?, 0xc0016c5cc0}, {0x25e9190?, 0xc0016ff9e0}, 0xc001601710, 0x0?)
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:286 +0x1c5
github.com/turbot/steampipe/pkg/db/db_client.(*DbClient).ExecuteInSession.func2()
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:161 +0xaa
created by github.com/turbot/steampipe/pkg/db/db_client.(*DbClient).ExecuteInSession in goroutine 91
	/home/runner/work/steampipe/steampipe/pkg/db/db_client/db_client_execute.go:153 +0x46f
```

Steampipe v0.21.7 w/ hub.steampipe.io/plugins/turbot/aws@latest  v0.131.0

**Comment by ParthaI** [comment]
Hi @blurayne, I'm sorry to hear about the problems you're encountering.

I'll investigate the issue and reach out if I need more details.

Thank you!

**Comment by blurayne** [comment]
`GROUP BY attached_instance_id` is of course wrong. But it shouldn't end in panic ;)

**Comment by ParthaI** [comment]
Hello, @blurayne, I've reviewed the issue and would like to share my observations. Please take a moment to review them.

- It appears that the issue mentioned does not originate from the plugin.
- The underlying cause seems to be Steampipe FDW's inability to parse the query.
- Below is a modified query for you to test in your environment. Please give it a try.

```sql
WITH CTE AS (
    SELECT
        network_interface_id,
        description,
        attached_instance_id
    FROM
        aws_ec2_network_interface
)

SELECT 
    array_agg(network_interface_id) AS eni_ids, 
    (SELECT array_agg(DISTINCT description) FROM CTE) AS distinct_descriptions, 
    (SELECT array_agg(DISTINCT attached_instance_id) FROM CTE WHERE attached_instance_id IS NOT NULL) AS distinct_instance_ids, 
    COUNT(DISTINCT attached_instance_id) AS count_of_attached_instances
FROM 
    CTE;
```

Result:

```
[
 {
  "count_of_attached_instances": 0,
  "distinct_descriptions": ",DO NOT DELETE - Amazon MSK network interface for cluster arn:aws:kafka:ap-south-1:333333333333:cluster/demo-cluster-1/1afa400c-102f-4a53-b0f9-879c1938f48d-2.",
  "distinct_instance_ids": null,
  "eni_ids": "eni-0367b9c247b7b0f24,eni-08e1ccbf253ff50f2,eni-0c2686f1f9e235968,eni-0cabf85a2d26fb069,eni-0d77ea35cc4e2e062,eni-0c728ef75927276db,eni-05ea0b14cce4596e0,eni-03281edd4663f4424"
 }
]
```

A few key points about the query above:
- If the intent is to aggregate these values across all network interfaces in your dataset, but you want to ensure distinct lists for `description` and `attached_instance_id`, while also counting the number of non-null `attached_instance_id` entries, you can use the `GROUP BY `clause. However, if you're aggregating without a specific grouping condition (i.e., you want a summary over your entire dataset), you do not necessarily need a `GROUP BY` clause.
- If `attached_instance_id` can be `NULL` and you want to count only non-null values, `COUNT(DISTINCT attached_instance_id)` will automatically ignore `NULL` values. If your logic requires different handling of `NULL` values or any other specific case, you might need to adjust the query further.

_Note: This query assumes that `attached_instance_id` can be `NULL` and specifically excludes `NULL` values from the `distinct_instance_ids` array. Adjustments might be needed based on the exact requirements and data specifics._

If you have any further concerns please feel free to raise them here.

Thanks!

**Comment by ParthaI** [comment]
Hello, @blurayne, have you had the opportunity to review the previous comment?

**Comment by bigdatasourav** [comment]
Hey @blurayne, we're closing this issue as we haven't heard back from you, please feel free to reopen if you want to share anything. Thanks!
