### ISSUE TITLE
Failed to populate column 'akas' in aws_health_affected_entity, panic runtime error 😱

### ISSUE THREAD

**Issue by dalenewman** [turbot/steampipe-plugin-aws#2183]
**Describe the bug**
When I `select * from aws.aws_health_affected_entity` I get the error:
```
ERROR:  rpc error: code = Unknown desc = aws: failed to populate column 'akas': rpc error: code = Internal desc = transform EnsureStringArray failed with panic runtime error: invalid memory address or nil pointer dereference 
```

**Steampipe version (`steampipe -v`)**
Example: v0.22.2

**Plugin version (`steampipe plugin list`)**
Example: v0.137.0

**To reproduce**
When I `select * from aws.aws_health_affected_entity` I get the error:
```
ERROR:  rpc error: code = Unknown desc = aws: failed to populate column 'akas': rpc error: code = Internal desc = transform EnsureStringArray failed with panic runtime error: invalid memory address or nil pointer dereference 
```

**Expected behavior**
It should return some results, because I have 21 records from `select * from aws.aws_health_event` with lots of open and upcoming events.

**Additional context**
I am querying against an AWS gov-cloud account.

**Comment by ParthaI** [comment]
Hi @dalenewman, I'm sorry to hear about the issues you're encountering. Unfortunately, I was unable to make the `DescribeEvents` API call in our test environment since our current plan is `Basic`, and only Business or Enterprise plans can access the AWS Health API.

I've made some updates in the branch `issue-2183`, including adding a few log statements to the plugin code to help us delve deeper into the issues.

Could you please run the query with the log level set to `Debug` using the changes in the `issue-2183` branch, and then share the plugin logs from the folder `~/.steampipe/logs/plugin-*.log` (after removing any sensitive information)?

Here are the steps to run the query with the changes pushed to the branch `issue-2183`:
- Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-aws.git`
- Change to the directory: `cd steampipe-plugin-aws`
- Switch to the branch: `git checkout issue-2183`
- Build the plugin: `make`
- Set the log level: `export SP_LOG=DEBUG`
- Execute the query: `select * from aws_health_affected_entity`

Thanks for your help!

**Comment by dalenewman** [comment]
Attached 
[plugin-2024-05-06.log](https://github.com/turbot/steampipe-plugin-aws/files/15221050/plugin-2024-05-06.log)

**Comment by ParthaI** [comment]
Hello @dalenewman, thank you for providing the log details.

I've made another commit to the `issue-2183` branch that includes updates to the code to address the nil pointer dereference error.

Could you please pull the latest changes from the `issue-2183` branch into your local environment and attempt to run the query again after building the plugin locally?

Before you run the query, ensure that all Steampipe processes are terminated.
Additionally, if you don't encounter any errors, could you please share the results for the query select * from aws_health_affected_entity where akas is null;? Be sure to remove any sensitive information beforehand. I would like to understand the result set that might be contributing to the issue.

Thank you!

**Comment by dalenewman** [comment]
Attached Results.  Looks like an EC2 operational issue.  
[affected-entity-with-akas-null.csv](https://github.com/turbot/steampipe-plugin-aws/files/15235855/affected-entity-with-akas-null.csv)
[corresponding-event.csv](https://github.com/turbot/steampipe-plugin-aws/files/15235856/corresponding-event.csv)

![image](https://github.com/turbot/steampipe-plugin-aws/assets/933086/d1138d7b-286f-4afb-a3f5-4446f0948eac)

**Comment by ParthaI** [comment]
Thank you, @dalenewman, for providing the information. From the results, I can see that if we have an operational issue entity, there will not be an ARN for it. I believe the fix appears to be effective. I'll proceed with some code cleanup in the branch and prepare it for review. Thanks again for your assistance!
