### ISSUE TITLE
Let me query aws_ssoadmin_account_assignment without qualifiers

### ISSUE THREAD

**Issue by iainelder** [turbot/steampipe-plugin-aws#2317]
I want to list all the assignments in my Identity Center instance.

The [aws_ssoadmin_account_assignment](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ssoadmin_account_assignment) table should solve it with this query.

```sql
SELECT * FROM aws_ssoadmin_account_assignment;
```

But the query fails because it doesn't qualify the permission set ARN and the target account ID.

```
Error: rpc error: code = Internal desc = aws: rpc error: code = Internal desc = 'List' call for table 'aws_ssoadmin_account_assignment' is missing 2 required quals:
    column:'permission_set_arn' operator: =
    column:'target_account_id' operator: =
 (SQLSTATE HV000)
```

I try to work around it with this query to join a list of organization accounts and a list of permission sets. It gives the same error.

```sql
SELECT assignment.*
FROM aws_ssoadmin_account_assignment AS assignment
INNER JOIN aws_organizations_account AS ac ON (ac.account_id = assignment.target_account_id)
INNER JOIN aws_ssoadmin_permission_set AS ps ON (ps.arn = assignment.permission_set_arn)
;
```

Steampipe can provide more value here by abstracting away all the required parameters of the underlying [ListAccountAssignments API](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListAccountAssignments.html). If I want **all** the assignments, Steampipe should figure out the API calls to make that happen.

[aws-sso-uitil](https://github.com/benkehoe/aws-sso-util/blob/master/docs/lookup.md) has a command to solve the problem called `aws-sso-utill admin assignments`. The Steampipe table could copy its solution.

> aws-sso-util takes care of this, by [looping over all the accounts in your organization](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html), then [over all the permission sets in each account](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListPermissionSetsProvisionedToAccount.html) and then [over all principals with that permission set in that account](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListAccountAssignments.html).

**Comment by ParthaI** [comment]
Hello @iainelder,  

Thank you for sharing your thoughts; they are greatly appreciated! Initially, we considered designing the table without any required qualifiers. However, due to concerns about query timing and performance, we decided not to proceed with that approach.  

To address this need, we have added multiple tables (`aws_organizations_account` and `aws_ssoadmin_permission_set`) to help users retrieve all account assignments across their organization, ensuring a more efficient and scalable solution.

> I try to work around it with this query to join a list of organization accounts and a list of permission sets. It gives the same error.

      SELECT assignment.*
      FROM aws_ssoadmin_account_assignment AS assignment
      INNER JOIN aws_organizations_account AS ac ON (ac.account_id = assignment.target_account_id)
      INNER JOIN aws_ssoadmin_permission_set AS ps ON (ps.arn = assignment.permission_set_arn)
      ;

From my previous experience, the generation of a QUERY PLAN plays a crucial role in determining the behavior and performance of a query, especially when it involves joining multiple tables. QUERY PLAN outlines the sequence of operations the database engine will execute, such as which indexes to use, the order of table scans, and the method of joining tables (e.g., nested loops, hash joins).

Would you mind trying to update your query using a Common Table Expression (CTE), as suggested in discussions for similar issues?
Reference:
- https://github.com/turbot/steampipe-plugin-aws/issues/1723#issuecomment-1554166003
- https://github.com/turbot/steampipe-plugin-aws/issues/2096#issuecomment-1983530619

This approach may help simplify the query structure and improve readability or performance. Please feel free to reach out if you need further clarification or assistance!

Thanks!

**Comment by ParthaI** [comment]
Hello @iainelder,  

We haven’t heard back in a while, so we’ll go ahead and close this issue for now. If the concern persists or if you have more details to share, please feel free to reopen the issue, and we’ll gladly assist you further.  

Thank you for your understanding!

**Comment by iainelder** [comment]
Hi, @ParthaI . Thanks for your response.

I found a different approach to solve whatever problem I was working on at the time.

I'm not in a position now to try your suggestions. If the problem comes up again, I'll take another look.
