### ISSUE TITLE
If no profile is provided, no error is provided to the user and the query "hangs".

### ISSUE THREAD

**Issue by mildebrandt** [turbot/steampipe-plugin-aws#698]
If I don't supply any AWS profile information, queries sit at `Loading results` forever.

```
$ steampipe query
Welcome to Steampipe v0.9.0
For more information, type .help
> select tags from aws_ecs_cluster
⠧ Loading results... 
```

If I set the `AWS_PROFILE` env var first, then things work as expected.

**Steampipe version (`steampipe -v`)**
v0.9.0

**Plugin version (`steampipe plugin list`)**
v0.36.0

**Comment by mildebrandt** [comment]
Thanks for the fix! 

While it doesn't hang anymore, the message doesn't lead me to knowing how to fix it myself:
```
> select title, instance_id from aws_ec2_instance
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by cbruno10** [comment]
@mildebrandt Agree, the message from AWS in this case isn't very helpful, especially since provider chains are really only referenced when using the SDK directly. We'll look into improving the error message we return, which should make it easier to debug/fix the issue. I've created https://github.com/turbot/steampipe-plugin-aws/issues/760 to track this issue - if you have any other feedback, feel free to add onto this issue.

Thanks again for reporting this bug!

**Comment by mildebrandt** [comment]
I appreciate it, thanks!
