### ISSUE TITLE
Workspaces "no such host" errrors

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-plugin-aws#830]
**Describe the bug**
When using all regions in aws.spc and querying workspaces (select * from aws_workspaces_workspace) it is always erroring with some regional endpoint not existing.

**Steampipe version (`steampipe -v`)**
Example: v0.10.0

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------+---------+-------------+
| Name                                       | Version | Connections |
+--------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest | 0.42.2  | aws         |
+--------------------------------------------+---------+-------------+

**To reproduce**
Set ~/.steampipe/config/aws.spc to all no opt in required commercial regions

**Expected behavior**
For regions in which workspaces does not exist a graceful fail in that region should occur and other regions should continue as normal.

**Additional context**
Error: RequestError: send request failed
caused by: Post "https://workspaces.us-west-1.amazonaws.com/": dial tcp: lookup workspaces.us-west-1.amazonaws.com on 172.31.0.2:53: no such host

This has also happened on ap-northeast-1. Seems random as to whichever happens to error first.

**Comment by e-gineer** [comment]
Thanks for letting us know about this issue @twratl! Great to see you using Steampipe for workspaces :-)

I believe we're not properly handling the fact that workspaces is not supported in those regions. We need to return zero rows for any region where the service is not available.

The changing of order will happen because Steampipe is running API calls in parallel, so the order of responses received will change.

In general, the fix is to either:
1. * Limit the regions to those supported at https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_workspaces_workspace.go#L27
2. * Catch "no such host" errors and return an empty list.
