### ISSUE TITLE
Route53 Records Query Issue

### ISSUE THREAD

**Issue by twratl** [turbot/steampipe-plugin-aws#848]
**Describe the bug**
When running query `select * from aws_route53_record` an error is returned instead of results.
`Warning: executeQueries: query 1 of 1 failed: pq: rpc error: code = Internal desc = 'List' call is missing required quals: column:'zone_id' operator: =`

**Steampipe version (`steampipe -v`)**
v0.10.0

**Plugin version (`steampipe plugin list`)**
0.42.2

**To reproduce**
`steampipe query "select * from aws_route53_record"`

**Expected behavior**
A table of results where each row represents one route53 zone DNS record.

**Additional context**
N/A

**Comment by cbruno10** [comment]
Hey @twratl , for listing Route 53 records through the `aws_route53_record` table, you need to specify a hosted zone ID in the `zone_id` query, e.g., `select * from aws_route53_record where zone_id = 'Z10367881R3QOLJ00N0TEST';`. This is because the `aws_route53_record` table has the `zone_id` column set as a required list key column (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_route53_record.go#L22).

You can also join this table with the `aws_route53_zone` table to list all records for all zones, e.g.,
```sql
select
  r.name,
  r.zone_id,
  r.type,
  jsonb_pretty(r.records)
from
  aws_route53_record as r,
  aws_route53_zone as z
where
  r.zone_id = z.id;
```

**Comment by twratl** [comment]
Snap! Thanks for setting me straight. I will most certainly be using that query you provided! Much appreciated.

**Comment by e-gineer** [comment]
@twratl FYI there are lots of good example queries for this table in the hub docs - https://hub.steampipe.io/plugins/turbot/aws/tables/aws_route53_record
