### ISSUE TITLE
Support for ECR enhanced scanning

### ISSUE THREAD

**Issue by uname223** [turbot/steampipe-plugin-aws#915]
**Describe the bug**
Currently images scanned by the enhanced scanning does not provide proper scan results in the query

**Steampipe version (`steampipe -v`)**
0.12.2

**Plugin version (`steampipe plugin list`)**
0.49.0

**To reproduce**
select * from aws_ecr_repository

or

select
  repository_name,
  detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'INFORMATIONAL' as informational_severity_counts,
  detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'LOW' as low_severity_counts,
  detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'MEDIUM' as medium_severity_counts
from
  aws_ecr_repository,
  jsonb_array_elements(image_details) as details,
  jsonb(details) as detail;

**Expected behavior**
It would be good to be able to query also enhanced scanning results

**Additional context**
Enhanced scanning has been intorduced on re:Invent 2021
https://aws.amazon.com/blogs/containers/container-scanning-updates-in-amazon-ecr-private-registries-using-amazon-inspector/

**Comment by rajlearner17** [comment]
@uname223 Appreciate using Steampipe!!
While we are looking into this, if you can help us understand your use case for this and what way Stampipe is helping you? This will help us to prioritize. Thanks !!

**Comment by uname223** [comment]
hi @rajlearner17 I think the issue might be on AWS side - https://github.com/aws/containers-roadmap/issues/1662 

But in general it's helpful to see how many images with critical vulnerabilities we have in the registry so we can investigate further if they are deployed anywhere

**Comment by ParthaI** [comment]
https://github.com/aws/aws-cli/issues/6759

**Comment by misraved** [comment]
Thanks @uname223 for your patience. After having some discussion with the `aws-cli` team (Reference - [issue](https://github.com/aws/aws-cli/issues/6759)), we were able to add a new column `image_scanning_findings` to `aws_ecr_repository` table in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/937).

We would love your feedback on the above PR. 

In order to run and test the PR, please follow the steps below:

1. Clone the repository by using the command `git clone https://github.com/turbot/steampipe-plugin-aws.git`
2. Run `cd steampipe-plugin-aws`
3. Switch to the PR branch (in this case `git switch issue-915`)
4. Run the `make` command
5. Run the following set of queries to analyse the information - 
```
select * from aws_ecr_repository

or

select
repository_name,
detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'INFORMATIONAL' as informational_severity_counts,
detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'LOW' as low_severity_counts,
detail -> 'ImageScanFindingsSummary' -> 'FindingSeverityCounts' ->> 'MEDIUM' as medium_severity_counts
from
aws_ecr_repository,
jsonb_array_elements(image_details) as details,
jsonb(details) as detail;

```

Please let us know if the output data looks good and if you need more information around it 👍

**Comment by uname223** [comment]
Hi, I followed your steps but got an issue

`Error: AccessDeniedException: User: arn:aws:sts::****:assumed-role/ViewOnly/***** is not authorized to perform: inspector2:ListFindings on resource: arn:aws:inspector2:****:*****:/findings/list
        status code: 400, request id: bedc472f-251b-4d8a-8692-b0a8f312d7c9 (SQLSTATE HV000)`

**Comment by uname223** [comment]
After attaching policy `AmazonInspector2ReadOnlyAccess` to my `ViewOnly` role it finally worked out! I think it should be mentioned in the documentation after the release

**Comment by misraved** [comment]
@uname223 Thank you so much for the feedback !! 

We will definitely mention it in the documentation so that it becomes more transparent 👍 .
