### ISSUE TITLE
Add table_aws_accessanalyzer_analyzer

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-aws#96]
1.21 Ensure that IAM Access analyzer is enabled (Automated)

AWS IAM Access Analyzer helps you identify the resources in your organization and accounts, such as Amazon S3 buckets or IAM roles, that are shared with an external entity. This lets you identify unintended access to your resources and data. Access Analyzer identifies resources that are shared with external principals by using logic-based reasoning to analyze the resource-based policies in your AWS environment. IAM Access Analyzer continuously monitors all policies for S3 bucket, IAM roles, KMS(Key Management Service) keys, AWS Lambda functions, and Amazon SQS(Simple Queue Service) queues.

**Comment by e-gineer** [comment]
@MichaelBurgess Did you make any progress on this previously? Is there something the team can pick up on?

**Comment by MichaelBurgess** [comment]
@e-gineer / @debabrat-git I worked on the AWS IAM Access Advisor table (`aws_iam_access_advisor `) which is in the published plugin. Not aware we did anything on AWS Access Analyzer yet - @johnsmyth that's right yeah?

**Comment by johnsmyth** [comment]
Thats right @MichaelBurgess.  I think we took a quick look but decided that `aws_iam_access_advisor` solved the problem we were interested in.  It was also more bang for the buck because Access Analyzer needs to be set up, configured, and run, whereas `aws_iam_access_advisor` is just available.  This service will need more than one table though - analyzers, findings, perhaos analyzed resources...
